apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-lab-app
  labels:
    app: incident-lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident-lab-app
  template:
    metadata:
      labels:
        app: incident-lab-app
    spec:
      containers:
        - name: incident-lab-app
          image: incident-lab-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: incident-lab-config
                  key: APP_MESSAGE
            - name: REQUIRED_CONFIG
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
